fix: add documentation of UserInfo policy
gravitee-io/gravitee-policy-openid-connect-userinfo pull request #24
Opened 2022-07-08 11:52 UTC by ytvnr

2022-07-08 13:16 UTC, mouligno requested changes

2022-07-08 13:16 UTC, mouligno commented on README.adoc
> +NOTE: If no Oauth2 resource is defined for the policy, or it is not well configured, the request will fail with a 401 status. More information will be available in `WWW_Authenticate` header
```suggestion
NOTE: If no Oauth2 resource is defined for the policy, or misconfigured, the request will fail with a 401 status. More information will be available in `WWW_Authenticate` header
```

2022-07-08 13:16 UTC, mouligno commented
@ivan-gravitee any thoughts on this documentation ?

2022-07-08 14:00 UTC, ivan-gravitee requested changes
Looks good - added a few small suggestions.

2022-07-08 14:00 UTC, ivan-gravitee commented on README.adoc
> +NOTE: If no Oauth2 resource is defined for the policy, or it is not well configured, the request will fail with a 401 status. More information will be available in `WWW_Authenticate` header
```suggestion
NOTE: The request will fail with a 401 status If the policy's Oauth2 resource is misconfigured or not defined at all. To troubleshoot this, check the `WWW_Authenticate` header for more information.
```

2022-07-08 14:00 UTC, ivan-gravitee commented on README.adoc
> +NOTE: If no Oauth2 resource is defined for the policy, or it is not well configured, the request will fail with a 401 status. More information will be available in `WWW_Authenticate` header
please see the other variant below

2022-07-08 14:00 UTC, ivan-gravitee commented on README.adoc
> +You can configure the policy with the following options:
```suggestion
Use the following options to configure the policy:
```

2022-07-08 14:00 UTC, ivan-gravitee commented on README.adoc
> +You can use the `policy-openid-userinfo` to get the OpenId Connect user info from an OAuth2 resource through its UserInfo endpoint.
```suggestion
Use the `policy-openid-userinfo` to get the OpenId Connect user info from an OAuth2 resource through its `UserInfo` endpoint.
```

2022-07-08 14:00 UTC, ivan-gravitee commented on README.adoc
> +|extractPayload||When `true`, the payload of the response from UserInfo endpoint is set in the gateway `openid.userinfo.payload` attribute|boolean|
```suggestion
|extractPayload||When set to `true`, the payload of the response from the UserInfo endpoint is set in the `openid.userinfo.payload` gateway attribute|boolean|
```

2022-07-11 07:59 UTC, ivan-gravitee approved these changes
LGTM

2022-07-11 12:15 UTC, merged

2022-07-11 12:17 UTC, graviteeio commented
:tada: This PR is included in version 1.5.2 :tada:

The release is available on:
- `1.5.2`
- [GitHub release](https://github.com/gravitee-io/gravitee-policy-openid-connect-userinfo/releases/tag/1.5.2)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: